version: "3.3"  # optional since v1.27.0
services:
  rest-gateway:
    build: ./rest-gateway
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
  calculator-service:
    build: ./calculator-service
    depends_on:
      - rabbitmq
      - redis
  rabbitmq:
    image: rabbitmq:3.9.17-alpine
  redis:
    image: redis:7.0.0-alpine3.16